#!/bin/sh

# Copyright (C) 2022 Canonical Ltd.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

if [ ! -d $SNAP_COMMON/host-hunspell ]; then
  echo "No host-hunspell, skipping"
  exit 0
fi;
DICPATH=$SNAP_COMMON/snap-hunspell

if [ -d $DICPATH ]; then
  # Cleanup on each refresh, ensure we have uptodate content
  find $DICPATH -type l -name "*.dic" -or -name "*.aff" | xargs rm
else
  mkdir -p $DICPATH
fi

for dic in $(find $SNAP_COMMON/host-hunspell/ -name "*.dic");
do
  dic_file=$(basename $dic)
  aff_file="${dic_file%%.dic}.aff"
  ln -s $SNAP/usr/share/hunspell/${dic_file} $DICPATH/${dic_file}
  ln -s $SNAP/usr/share/hunspell/${aff_file} $DICPATH/${aff_file}
done;
